main:
  mlflow_tracking_url: "http://test:5000/"
  #mlflow_tracking_url: null
  experiment_name: airflow_prod_all_genre_classification
  execute_steps:
    - ml
random_forest_pipeline:
  export_artifact: "model_export"
prediction:
  daily_path: "./../daily_data/daily_data_20220601.csv"
  prediction_daily_path: "./../predicted_daily_data/predicted_daily_data_20220601.csv"