FROM puckel/docker-airflow:1.10.9

USER root

RUN pip install evidently
RUN pip install mlflow==1.10.0
RUN pip install --upgrade protobuf==3.20.0
ENV GIT_PYTHON_REFRESH quiet

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

